from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
row = list()
soma = list()
mini = list()
ma = list()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabela_de_Jogos = QtWidgets.QTableWidget(self.centralwidget)
        self.Tabela_de_Jogos.setObjectName("Tabela_de_Jogos")
        self.Tabela_de_Jogos.setColumnCount(7)
        self.Tabela_de_Jogos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_de_Jogos.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.Tabela_de_Jogos, 0, 0, 1, 3)
        self.pontos_do_jogo = QtWidgets.QLabel(self.centralwidget)
        self.pontos_do_jogo.setObjectName("pontos_do_jogo")
        self.gridLayout.addWidget(self.pontos_do_jogo, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.gridLayout.addWidget(self.label, 1, 2, 3, 1)
        self.Caixa_de_pontos = QtWidgets.QLineEdit(self.centralwidget)
        self.Caixa_de_pontos.setText("")
        self.Caixa_de_pontos.setObjectName("Caixa_de_pontos")
        self.gridLayout.addWidget(self.Caixa_de_pontos, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton.clicked.connect(lambda: self.adicionar())
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def adicionar(self):
        pontos = self.Caixa_de_pontos.text()
        try:
            int(pontos)
            if int(pontos) < 0:
                pontos = 'Sou negativo'
            int(pontos)
        except:
            QMessageBox.about(self.centralwidget, 'ERRO', 'Pontuação Invalida')
        else:
            rowCount = self.Tabela_de_Jogos.rowCount()
            self.Tabela_de_Jogos.insertRow(rowCount)
            row.append(pontos)
            soma.append(int(pontos))
            media = sum(soma) / len(soma)
            if len(row) == 1:
                self.Tabela_de_Jogos.setItem(len(row)-1, 0, QtWidgets.QTableWidgetItem(str(len(row))))
                self.Tabela_de_Jogos.setItem(len(row)-1, 1, QtWidgets.QTableWidgetItem(pontos))
                self.Tabela_de_Jogos.setItem(len(row)-1, 2, QtWidgets.QTableWidgetItem(min(row)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 3, QtWidgets.QTableWidgetItem(max(row)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 4, QtWidgets.QTableWidgetItem(str(len(mini))))
                self.Tabela_de_Jogos.setItem(len(row)-1, 5, QtWidgets.QTableWidgetItem(str(len(ma))))
                self.Tabela_de_Jogos.setItem(len(row)-1, 6, QtWidgets.QTableWidgetItem(str(int(media))))
                mini.append(int(pontos))
                ma.append(int(pontos))
            else:
                if soma[-1] < mini[-1]:
                    mini.append(int(pontos))
                if soma[-1] > ma[-1]:
                    ma.append(int(pontos))
                self.Tabela_de_Jogos.setItem(len(row)-1, 0, QtWidgets.QTableWidgetItem(str(len(row))))
                self.Tabela_de_Jogos.setItem(len(row)-1, 1, QtWidgets.QTableWidgetItem(pontos))
                self.Tabela_de_Jogos.setItem(len(row)-1, 2, QtWidgets.QTableWidgetItem(min(row)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 3, QtWidgets.QTableWidgetItem(max(row)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 4, QtWidgets.QTableWidgetItem(str(len(mini)-1)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 5, QtWidgets.QTableWidgetItem(str(len(ma)-1)))
                self.Tabela_de_Jogos.setItem(len(row)-1, 6, QtWidgets.QTableWidgetItem(str(int(media))))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proway"))
        item = self.Tabela_de_Jogos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Jogo"))
        self.Tabela_de_Jogos.setColumnWidth(0, 40)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Placar"))
        self.Tabela_de_Jogos.setColumnWidth(1, 45)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mínimo da Temporada"))
        self.Tabela_de_Jogos.setColumnWidth(2, 130)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Máximo da Temporada"))
        self.Tabela_de_Jogos.setColumnWidth(3, 130)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quebra recorde mín."))
        self.Tabela_de_Jogos.setColumnWidth(4, 125)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Quebra recorde máx."))
        self.Tabela_de_Jogos.setColumnWidth(5, 125)
        item = self.Tabela_de_Jogos.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Média de Pontos"))
        self.Tabela_de_Jogos.setColumnWidth(6, 150)
        self.pontos_do_jogo.setText(_translate("MainWindow", "Pontuação do Jogo"))
        self.pushButton.setText(_translate("MainWindow", "Adicionar Pontuação"))



import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())
